In [1]:
import pandas as pd

In [4]:
county_data = pd.read_csv('County_zhvi_uc_sfrcondo_tier_0.33_0.67_sm_sa_month.csv')

In [ ]:
dates = county_data.columns[9:] # These are the timestamps
price_by_county = pd.DataFrame(county_data[dates].values.T, columns=county_data['RegionName'], index=dates) # Transposing the dataset, now using the RegionName (ZIP code) as the columns, dates for the index, and transposing the housing data
price_by_county

,RegionID,SizeRank,RegionName,RegionType,StateName,State,Metro,StateCodeFIPS,MunicipalCodeFIPS,2000-01-31,...,2024-03-31,2024-04-30,2024-05-31,2024-06-30,2024-07-31,2024-08-31,2024-09-30,2024-10-31,2024-11-30,2024-12-31
0,3101,0,Los Angeles County,county,CA,CA,"Los Angeles-Long Beach-Anaheim, CA",6,37,205554.642143,...,842828.125468,843458.023150,846590.488371,848657.557658,852267.676628,857411.008912,863957.219674,869036.446028,873116.490139,876489.981962
1,139,1,Cook County,county,IL,IL,"Chicago-Naperville-Elgin, IL-IN-WI",17,31,146088.131319,...,295891.891394,298514.510384,300331.667498,301377.039259,302029.073728,302846.384103,303511.080209,303864.098187,304254.182907,304914.611846
2,1090,2,Harris County,county,TX,TX,"Houston-The Woodlands-Sugar Land, TX",48,201,109502.880748,...,282099.985083,283142.592334,283733.994057,283615.859587,283246.105196,282907.172194,282692.273148,282325.752609,281874.816774,281642.532453
3,2402,3,Maricopa County,county,AZ,AZ,"Phoenix-Mesa-Chandler, AZ",4,13,143224.384045,...,467120.843290,468892.771578,470292.903957,470461.256487,469857.613304,468743.383602,467798.713506,467070.117625,466405.864875,465828.629769
4,2841,4,San Diego County,county,CA,CA,"San Diego-Chula Vista-Carlsbad, CA",6,73,213034.659393,...,911324.080512,921505.174834,930221.439635,934686.727793,936123.029271,935687.520148,935242.345948,934533.913892,934725.657369,935232.664342
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3068,846,3206,Banner County,county,NE,NE,"Scottsbluff, NE",31,7,NaN,...,321125.066597,324004.896959,327386.466115,328069.339347,330165.658998,336736.175154,346631.949352,354998.496627,358646.215997,363180.460914
3069,1648,3207,Daggett County,county,UT,UT,NaN,49,9,NaN,...,321388.066928,321448.379443,320133.501640,318038.022608,315829.862113,315766.403474,318169.837605,322748.075604,326448.913102,330270.364833
3070,1432,3208,Thomas County,county,NE,NE,NaN,31,171,NaN,...,162545.502097,163043.652064,163376.474022,163708.115429,163511.719807,164047.103362,164787.407684,166054.747665,166257.891113,166435.634476
3071,2794,3212,McPherson County,county,NE,NE,"North Platte, NE",31,117,NaN,...,296002.925100,301582.530690,306218.863367,308687.099937,311291.959869,318725.125071,329326.702388,339183.091984,344650.536347,350922.241689
3072,2825,3214,Petroleum County,county,MT,MT,NaN,30,69,NaN,...,151494.206925,154277.155271,156216.645356,157035.155136,157017.983872,158653.532384,161280.339942,165289.537724,168560.091132,173025.297990